services:
  app:
    build:
      context: ./docker
    container_name: geo-parser
    volumes:
      - .:/var/www
    # If your application exposes a port, uncomment the following lines and change
    # the port numbers as needed. The first number is the host port and the second
    # is the port inside the container.
    ports:
      - 9000:9000

